// GtkSharp.Generation.ObjectField.cs - autogenerated field glue
//
// Copyright (c) 2004 Novell, Inc.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of version 2 of the GNU General Public
// License as published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public
// License along with this program; if not, write to the
// Free Software Foundation, Inc., 59 Temple Place - Suite 330,
// Boston, MA 02111-1307, USA.


using System.Xml;
using GapiCodegen.Generatables;
using GapiCodegen.Util;

namespace GapiCodegen {
	public class ObjectField : FieldBase {

		public ObjectField (XmlElement element, ClassBase container_type) : base (element, container_type){
			if (CType == "char*" || CType == "gchar*")
				ctype = "const-" + CType;
		}

		public ObjectField (XmlElement element, ClassBase container_type, FieldBase abi_field) : base (element, container_type) {
			if (CType == "char*" || CType == "gchar*")
				ctype = "const-" + CType;
		}

		internal override bool Writable {
			get {
				return Element.GetAttributeAsBoolean ("writeable");
			}
		}

		protected override string DefaultAccess {
			get {
				return "private";
			}
		}
	}
}

